export const airportCodes = {
  "ATL": {
    "iataCode": "ATL",
    "name": "Hartsfield-Jackson Atlanta International Airport",
    "city": "Atlanta",
    "country": "United States",
    "latitude": 33.6407,
    "longitude": -84.4277,
    "website": "https://www.atl.com/"
  },
  "DFW": {
    "iataCode": "DFW",
    "name": "Dallas/Fort Worth International Airport",
    "city": "Dallas",
    "country": "United States",
    "latitude": 32.8998,
    "longitude": -97.0403,
    "website": "https://www.dfwairport.com/"
  },
  "DEN": {
    "iataCode": "DEN",
    "name": "Denver International Airport",
    "city": "Denver",
    "country": "United States",
    "latitude": 39.8561,
    "longitude": -104.6737,
    "website": "https://www.flydenver.com/"
  },
  "ORD": {
    "iataCode": "ORD",
    "name": "O'Hare International Airport",
    "city": "Chicago",
    "country": "United States",
    "latitude": 41.9786,
    "longitude": -87.9048,
    "website": "https://www.flychicago.com/ohare/en/home/"
  },
  "LAX": {
    "iataCode": "LAX",
    "name": "Los Angeles International Airport",
    "city": "Los Angeles",
    "country": "United States",
    "latitude": 33.9416,
    "longitude": -118.4085,
    "website": "https://www.flylax.com/"
  },
  "CLT": {
    "iataCode": "CLT",
    "name": "Charlotte Douglas International Airport",
    "city": "Charlotte",
    "country": "United States",
    "latitude": 35.2140,
    "longitude": -80.9431,
    "website": "https://cltairport.com/"
  },
  "MIA": {
    "iataCode": "MIA",
    "name": "Miami International Airport",
    "city": "Miami",
    "country": "United States",
    "latitude": 25.7933,
    "longitude": -80.2906,
    "website": "https://www.miami-airport.com/"
  },
  "JFK": {
    "iataCode": "JFK",
    "name": "John F. Kennedy International Airport",
    "city": "New York",
    "country": "United States",
    "latitude": 40.6413,
    "longitude": -73.7781,
    "website": "https://www.jfkairport.com/"
  },
  "EWR": {
    "iataCode": "EWR",
    "name": "Newark Liberty International Airport",
    "city": "Newark",
    "country": "United States",
    "latitude": 40.6924,
    "longitude": -74.1687,
    "website": "https://www.newarkairport.com/"
  },
  "SFO": {
    "iataCode": "SFO",
    "name": "San Francisco International Airport",
    "city": "San Francisco",
    "country": "United States",
    "latitude": 37.6216,
    "longitude": -122.3793,
    "website": "https://www.flysfo.com/"
  },
  "DTW": {
    "iataCode": "DTW",
    "name": "Detroit Metropolitan Airport",
    "city": "Detroit",
    "country": "United States",
    "latitude": 42.2121,
    "longitude": -83.3488,
    "website": "https://www.metroairport.com/"
  },
  "BOS": {
    "iataCode": "BOS",
    "name": "Logan International Airport",
    "city": "Boston",
    "country": "United States",
    "latitude": 42.3656,
    "longitude": -71.0096,
    "website": "https://www.massport.com/logan-airport/"
  },
  "PHL": {
    "iataCode": "PHL",
    "name": "Philadelphia International Airport",
    "city": "Philadelphia",
    "country": "United States",
    "latitude": 39.8720,
    "longitude": -75.2433,
    "website": "https://www.phl.org/"
  },
  "LGA": {
    "iataCode": "LGA",
    "name": "LaGuardia Airport",
    "city": "New York",
    "country": "United States",
    "latitude": 40.7769,
    "longitude": -73.8740,
    "website": "https://www.laguardiaairport.com/"
  },
  "IAD": {
    "iataCode": "IAD",
    "name": "Washington Dulles International Airport",
    "city": "Washington, D.C.",
    "country": "United States",
    "latitude": 38.9531,
    "longitude": -77.4565,
    "website": "https://www.flydulles.com/"
  },
  "OAK": {
    "iataCode": "OAK",
    "name": "Oakland International Airport",
    "city": "Oakland",
    "country": "United States",
    "latitude": 37.7214,
    "longitude": -122.2208,
    "website": "https://www.oaklandairport.com/"
  }
}





export const airportsInfos = [
  {
    id: 1,
    city: "Atlanta",
    code: "ATL",
    state: "GA",
    country: "USA",
    name: "Hartsfield-Jackson Atlanta International Airport",
    website: "https://www.atl.com/",
    latitude: 33.6407,
    longitude: -84.4277,
  },
  {
    id: 2,
    city: "Dallas",
    code: "DFW",
    state: "TX",
    country: "USA",
    name: "Dallas/Fort Worth International Airport",
    website: "https://www.dfwairport.com/",
    latitude: 32.8968,
    longitude: -97.0380,
  },
  {
    id: 3,
    city: "Denver",
    code: "DEN",
    state: "CO",
    country: "USA",
    name: "Denver International Airport",
    website: "https://www.flydenver.com/",
    latitude: 39.8561,
    longitude: -104.6737,
  },
  {
    id: 4,
    city: "Chicago",
    code: "ORD",
    state: "IL",
    country: "USA",
    name: "O'Hare International Airport",
    website: "https://www.flychicago.com/ohare/en/home/",
    latitude: 41.9796,
    longitude: -87.9045,
  },
  {
    id: 5,
    city: "Los Angeles",
    code: "LAX",
    state: "CA",
    country: "USA",
    name: "Los Angeles International Airport",
    website: "https://www.flylax.com/",
    latitude: 33.9416,
    longitude: -118.4085,
  },
  {
    id: 6,
    city: "Charlotte",
    code: "CLT",
    state: "NC",
    country: "USA",
    name: "Charlotte Douglas International Airport",
    website: "https://www.cltairport.com/",
    latitude: 35.2140,
    longitude: -80.9431,
  },
  {
    id: 7,
    city: "Miami",
    code: "MIA",
    state: "FL",
    country: "USA",
    name: "Miami International Airport",
    website: "https://www.miami-airport.com/",
    latitude: 25.7933,
    longitude: -80.2906,
  },
  {
    id: 8,
    city: "New York",
    code: "JFK",
    state: "NY",
    country: "USA",
    name: "John F. Kennedy International Airport",
    website: "https://www.jfkairport.com/",
    latitude: 40.6413,
    longitude: -73.7781,
  },
  {
    id: 9,
    city: "Newark",
    code: "EWR",
    state: "NJ",
    country: "USA",
    name: "Newark Liberty International Airport",
    website: "https://www.newarkairport.com/",
    latitude: 40.6413,
    longitude: -74.1715,
  },
  {
    id: 10,
    city: "San Francisco",
    code: "SFO",
    state: "CA",
    country: "USA",
    name: "San Francisco International Airport",
    website: "https://www.flysfo.com/",
    latitude: 37.6213,
    longitude: -122.3790,
  },
  {
    id: 11,
    city: "Detroit",
    code: "DTW",
    state: "MI",
    country: "USA",
    name: "Detroit Metropolitan Wayne County Airport",
    website: "https://www.metroairport.com/",
    latitude: 42.2121,
    longitude: -83.3534,
  },
  {
    id: 12,
    city: "Boston",
    code: "BOS",
    state: "MA",
    country: "USA",
    name: "Logan International Airport",
    website: "https://www.massport.com/logan-airport/",
    latitude: 42.3656,
    longitude: -71.0096,
  },
  {
    id: 13,
    city: "Philadelphia",
    code: "PHL",
    state: "PA",
    country: "USA",
    name: "Philadelphia International Airport",
    website: "https://www.phl.org/",
    latitude: 39.8721,
    longitude: -75.2421,
  },
  {
    id: 14,
    city: "New York",
    code: "LGA",
    state: "NY",
    country: "USA",
    name: "LaGuardia Airport",
    website: "https://www.laguardiaairport.com/",
    latitude: 40.7769,
    longitude: -73.8740,
  },
  {
    id: 15,
    city: "Washington, D.C.",
    code: "IAD",
    state: "VA",
    country: "USA",
    name: "Washington Dulles International Airport",
    website: "https://flydulles.com/",
    latitude: 38.9531,
    longitude: -77.4565,
  },
  {
    id: 16,
    city: "Oakland",
    code: "OAK",
    state: "CA",
    country: "USA",
    name: "Oakland International Airport",
    website: "https://www.oaklandairport.com/",
    latitude: 37.7214,
    longitude: -122.2208,
  }
];

export const airlineLogos = 
  { 'UA': { name: 'United Airlines' },
  'B6': { name: 'JetBlue Airways' },
  'AA': { name: 'American Airlines' },
  'DL': { name: 'Delta Air Lines' },
  'F9': { name: 'Frontier Airlines' },};


